### ISSUE TITLE
Question about mariadb104* packages

### ISSUE THREAD

**Issue by zerocarbthirty** [iusrepo/mariadb104#1]
I really just have a question and I wasn't sure where to ask it.

If we have mariadb101u-server installed is it safe to just do this:

dnf --allowerasing install mariadb104-server

To upgrade it? 

I used a similar process to upgrade to php 7.4 and it worked alright, but I don't want to do anything crazy.

Thanks.

**Comment by carlwgeorge** [comment]
Yes, that should work fine from the package perspective.  I just tested that upgrade in a container and it resolved.  That's also what we recommend in [this wiki page for upgrading to mariadb102](https://github.com/iusrepo/mariadb102/wiki), and it still applies.  Make sure to also follow the [recommended steps from MariaDB](https://mariadb.com/kb/en/upgrading-between-major-mariadb-versions/).
